baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = 'PaperMod'

[module]

  [[module.mounts]]
    source = "assets/scss"
    target = "assets/scss"

#  [[module.mounts]]
#    source = "assets/css"
#    target = "assets/css"

  [[module.mounts]]
    source = "themes/PaperMod/assets/css"
    target = "assets/css"
