baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = 'PaperMod'

[params]
  CamelCase = true

[module]

  [[module.mounts]]
    source = "themes/PaperMod/images/screenshot.png"
    target = "static/images/screenshot.png"

  [[module.mounts]]
    source = "static"
    target = "static"
